#!/usr/bin/env bash
# Configure your Nginx server to redirect to another page

sudo apt-get update -y
sudo apt-get -y upgrade
sudo apt-get install -y nginx

sudo service nginx start

new_string="rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"

sudo sed -i "54i $new_string" /etc/nginx/sites-available/default

sudo service nginx reload
