#!/usr/bin/env bash
# Configure your Nginx server to redirect to another page

sudo apt-get update -y
sudo apt-get -y upgrade
sudo apt-get install -y nginx

sudo service nginx start

str="rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"

sudo sed -i "54i $str" /etc/nginx/sites-available/default

sudo service nginx restart
sudo service nginx reload
