#!/usr/bin/env bash
# Add a custom header to Nginx configuration

apt-get -y update
apt-get -y install nginx

sed -i '47i\    add_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default

echo "Hello World!" | tee /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

service nginx start
